project:
  type: website
  output-dir: docs

website:
  title: "Karthik's website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: About me
      - href: drinkUp.qmd
        text: DrinkUp 
      - href: dataVisualization.qmd
        text: Data Visualization
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left
    



